[config]
schemaVersion = "0.0.1"

[package]
namespace = "LeCloutPanda"
name = "SpeedyURLs" 
versionNumber = "2.1.0"
description = "Remove the 5-second cool-down on url consent popups."
websiteUrl = "https://github.com/lecloutpanda/SpeedyURLs"
containsNsfwContent = false

[package.dependencies] 
ResoniteModding-BepisLoader = "1.3.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./SpeedyURLs/bin/Release/SpeedyURLs.dll"
target = "plugins/SpeedyURLs/"

[[build.copy]]
source = "./SpeedyURLs/bin/Release/SpeedyURLs.pdb"
target = "plugins/SpeedyURLs/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[[build.copy]]
source = "./LICENSE"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]

[publish.categories]
resonite = [ "technicaltweaks", "misc" ]